### ISSUE TITLE
Problem with Unity version 2022

### ISSUE THREAD

**Issue by akchama** [sneakyevil/IL2CPP_Resolver#33]
I don't know if this is Unity version specific or not but when I looked up the methods thread methods were named like "mono_thread_attach" etc. instead of "il2cpp_..."

**Comment by DarknessSoulYouTube** [comment]
il2cpp_thread_attach(il2cpp_domain_get())?!

**Comment by akchama** [comment]
> il2cpp_thread_attach(il2cpp_domain_get())?!

I don't understand this reply. What I was referring to is how Il2CppResolver is trying to get the methods from the dll. When I opened the .dll with a disassembler these methods were starting with _mono__, hence not working with current implementation.

**Comment by sneakyevil** [comment]
IL2CPP Resolver has it literally in name that it should only work for il2cpp hence you're trying to use it on mono build instead il2cpp build. Read this: https://docs.unity3d.com/Manual/Mono.html and https://docs.unity3d.com/Manual/IL2CPP.html
