### ISSUE TITLE
Crash when try to access GetName()

### ISSUE THREAD

**Issue by Shillersan** [sneakyevil/IL2CPP_Resolver#34]
I tried to use the basic example to loop over `GameObject`s

```
std::string m_sObjectSubstring = "Player";

// Obtain list
Unity::il2cppArray<Unity::CGameObject*>* m_pObjects = Unity::Object::FindObjectsOfType<Unity::CGameObject>(UNITY_GAMEOBJECT_CLASS);

for (uintptr_t u = 0U; m_pObjects->m_uMaxLength > u; ++u)
{
    if (m_pObjects->m_pValues[u] == NULL) continue; // I added this because some values were NULL

    Unity::CGameObject* m_pObject = m_pObjects->m_pValues[u];
    if (!m_pObject) continue; // Just in-case

    // Obtaining object name and then converting it to std::string
    std::string m_sObjectName = m_pObject->GetName()->ToString();
    if (m_sObjectName.find(m_sObjectSubstring) != std::string::npos)
    {
        // logger.AddLog("Found Player!");
        break;
    }
}
```

I get an access violation error here: `std::string m_sObjectName = m_pObject->GetName()->ToString();`

**Comment by extremeblackliu** [comment]
its little bit confusing of looping array, but you should use
`Unity::CGameObject* m_pObject = m_pObjects->m_pValues->operator[](u);`
or
`Unity::CGameObject* m_pObject = m_pObjects->m_pValues->At(u);`

**Comment by Shillersan** [comment]
> its little bit confusing of looping array, but you should use `Unity::CGameObject* m_pObject = m_pObjects->m_pValues->operator[](u);` or `Unity::CGameObject* m_pObject = m_pObjects->m_pValues->At(u);`

Sorry if I am missing something but neither of these are defined.
`Cannot resolve symbol 'operator[]'`
`Cannot resolve symbol 'At'`

**Comment by extremeblackliu** [comment]
you have probably missing import header files.
the function is defined at 
https://github.com/sneakyevil/IL2CPP_Resolver/blob/main/Unity/Structures/il2cppArray.hpp#L17-L25

**Comment by Shillersan** [comment]
> operator[](u)

I see, I think you meant this: `Unity::CGameObject* m_pObject = m_pObjects->At(u);`, which worked! Thank you.

**Comment by extremeblackliu** [comment]
> Author

my fault.
