### ISSUE TITLE
Issue finding methods and method name

### ISSUE THREAD

**Issue by Shillersan** [sneakyevil/IL2CPP_Resolver#36]
I used to loop over methods but it prints gibberish like this: 
`U‹ìÿu\fÿu\x10ÿU\b‹M\x18ƒÄ\b‰\x1]ÃÌÌÌÌÌÌÌÌÌÌU‹ì‹U\x14ÿu\f‹B\bÿr\fƒì\x10\xf\x10`

```
Unity::il2cppClass* m_pClass = IL2CPP::Class::Find("MyClass");
void* methodIterator = nullptr;
Unity::il2cppMethodInfo* currentMethod = nullptr;

while ((currentMethod = IL2CPP::Class::GetMethods(m_pClass, &methodIterator)) != nullptr) {
    Logger::AddLog("%s", currentMethod->m_pName);
}
```

And is there a way to get methods with same name but different parameters?

**Comment by extremeblackliu** [comment]
read https://github.com/sneakyevil/IL2CPP_Resolver/blob/a260132fb7fa9fb724133128af9c945396afee8e/API/Class.hpp#L191

**Comment by Shillersan** [comment]
Apparently the issue was the `MethodInfo` struct is different from what is there in IL2CPP_Resolver. 
Unity version: **2022.3.8f1**

**Comment by extremeblackliu** [comment]
solved
