### ISSUE TITLE
i cant get value from UnityEngine.UI.Text

### ISSUE THREAD

**Issue by zxcbelaz** [sneakyevil/IL2CPP_Resolver#50]
### What is the game you are using with IL2CPP Resolver?

SCP:SL

### Details:

i need to get a text from gameconsole ui but i get nullptr for all variables I'm trying to get

### Minimal, Complete and Verifiable Example code:

```
                Unity::CComponent* sigma = Unity::GameObject::Find("GameConsole/Background/Console/Log/Text")->GetComponent("Text");
                std::string test = sigma->GetPropertyValue<std::string>("text");
                printf_s("sigma ptr: %p\n", sigma);
                printf_s("test value: %s\n", test);
```

**Comment by extremeblackliu** [comment]
better call GetComponent with fullname like e.g. `UnityEngine.GameObject`

**Comment by zxcbelaz** [comment]
thanks for the answer, it works, but there is 1 more question, how can I get a class that is in the game but is not on the object

**Comment by extremeblackliu** [comment]
You probably mean static classes (not attached to a gameobject as a component but persisting during gameplay), for which you can just use offset to dereference to Unity::Component*.
However, @fedes1to 's commit https://github.com/sneakyevil/IL2CPP_Resolver/pull/45 added new ways to interact with static classes, you might want to check it out yourself, I haven't tried it yet.

**Comment by zxcbelaz** [comment]
I can't use GetStaticValue. My Class::Find method doesn't find the class I need.
