### ISSUE TITLE
Game crashes on AddComponent method.

### ISSUE THREAD

**Issue by svorogaze** [sneakyevil/IL2CPP_Resolver#52]
### What is the game you are using with IL2CPP Resolver?

SCP:SL

### Details:

I am trying to add UnityEngine.Light to the Game Object named "Default Camera", but the game crashes on line` m_pObject->AddComponent(ptr)`;. 
Also, if I comment out `m_pObject->AddComponent(ptr);` line, `auto m_pObject = Unity::GameObject::Find("Default Camera");` seems to drop my fps from 200+ to 20(if I iterate over gameobjects manually fps doesn't decrease)

### Minimal, Complete and Verifiable Example code:

```
void ourmain() {
    Unity::il2cppClass* cptr = IL2CPP::Class::Find("UnityEngine.Light");
    Unity::il2cppObject* ptr = nullptr;
    if (cptr) {
       ptr = Unity::Object::New(cptr);
    }
    auto m_pObject = Unity::GameObject::Find("Default Camera");
    if (m_pObject && ptr && cptr) {
        m_pObject->AddComponent(ptr);
    }
}
```
In main:

```
IL2CPP::Initialize();
IL2CPP::Callback::Initialize();
IL2CPP::Callback::OnLateUpdate::Add(ourmain);
```

**Comment by svorogaze** [comment]
Thank you for your answer! Could you please clarify what you mean by "You're supposed to pass il2cppObject as type"?

**Comment by sneakyevil** [comment]
> Thank you for your answer! Could you please clarify what you mean by "You're supposed to pass il2cppObject as type"?

AddComponent takes il2cppObject pointer and the argument is called "SystemType" so you will need to use this to get the type:
https://github.com/sneakyevil/IL2CPP_Resolver/blob/9cb0706360c46516a4fd8c6578d1d603ca90b90a/API/Class.hpp#L50

**Comment by svorogaze** [comment]
Thank you, I rewrited it, but the game freezes in 5-10 seconds after I add component even if I do it only one time.
```
void ourmain() {
    static int counter = 0;
    std::string m_sObjectSubstring = "Default Camera";
    Unity::il2cppArray<Unity::CGameObject*>* m_pObjects = Unity::Object::FindObjectsOfType<Unity::CGameObject>(UNITY_GAMEOBJECT_CLASS);
    for (uintptr_t u = 0U; m_pObjects->m_uMaxLength > u; ++u) {
        Unity::CGameObject* m_pObject = m_pObjects->At(u);
        if (!m_pObject) continue;
        auto ptr = m_pObject->GetName();
        if (ptr) {
            std::string m_sObjectName = ptr->ToString();
            if (m_sObjectName.find(m_sObjectSubstring) != std::string::npos) {
                if (counter == 0) {
                    counter++;
                    Unity::il2cppClass* cptr = IL2CPP::Class::Find("UnityEngine.Light");
                    m_pObject->AddComponent(IL2CPP::Class::GetSystemType(cptr));
                    //auto pt = m_pObject->GetComponent("UnityEngine.Light");
                    //pt->SetPropertyValue("intensity", 10.f);
                }
            }
            
        }
    }
}
```
