### ISSUE TITLE
 Class::Find method doesn't find the class I need it return null_ptr

### ISSUE THREAD

**Issue by zxcbelaz** [sneakyevil/IL2CPP_Resolver#53]
### What is the game you are using with IL2CPP Resolver?

SCP:SL

### Details:

Class::Find method doesn't work with Any of classes

### Minimal, Complete and Verifiable Example code:

`
Unity::il2cppClass* CentralAuthScript = IL2CPP::Class::Find("Il2CppCentralAuth.CentralAuthManager");
printf_s("ptr: %p\n", CentralAuthScript);  // NOLINT(cert-err33-c)
`

**Comment by svorogaze** [comment]
Try getting it like this:
` Unity::il2cppClass* CentralAuthScript = IL2CPP::Class::Find("CentralAuth.CentralAuthManager");`
At least works for me
