### ISSUE TITLE
FetchFields results in an empty vector

### ISSUE THREAD

**Issue by svorogaze** [sneakyevil/IL2CPP_Resolver#54]
### What is the game you are using with IL2CPP Resolver?

SCP:SL

### Details:

I tried fetching fields of object with the name "Default Camera", but using `FetchFields` results in empty vector. I also tried the same for all objects in the game and they all had zero fetched fields, also tried it in other game(Phasmophobia) and it didn't work there either, so I assume the problem is my code

### Minimal, Complete and Verifiable Example code:

```
auto ptr = Unity::GameObject::Find("Default Camera");
if (ptr) {
     std::vector<Unity::il2cppFieldInfo*> vect;
     ptr->FetchFields(&vect);
     std::cout << vect.size() << '\n';
     for (auto i : vect) {
           std::cout << i->m_pName << ' ' << i->m_iOffset << '\n';
     }
}
```

**Comment by sneakyevil** [comment]
Maybe try attach debugger and step through the code and check what could be wrong?

**Comment by svorogaze** [comment]
SCP:SL prevents debugger from being attached, so I tried doing it in Phasmophobia, IL2CPP::Class::GetFields never returns value that is not nullptr, but I still don't understand what is wrong with my code

**Comment by sneakyevil** [comment]
Different unity version might change class to il2cppObject member or that function has been changed, either go debug and figure out what it is calling with pdb to unityplayer.dll or manually check it in static analyze via ghidra/ida and try fix it.
There shouldn't be anything wrong with your code.

**Comment by svorogaze** [comment]
Thank you for your answer! I found it in ida, could you please clarify what I need to do next? Do I need to find it's code and try to fix it(for some reason I can't find it's code in UnityPlayer.dll, I assume it's in dynamic library which is being loaded in LoadIl2cpp)
![Capturegit](https://github.com/sneakyevil/IL2CPP_Resolver/assets/68436858/92aad40a-b1e4-4855-804e-bfca234d7f74)
![Capturegit2](https://github.com/sneakyevil/IL2CPP_Resolver/assets/68436858/5157a39b-63e1-476d-9000-2ca223f465fb)
![image](https://github.com/sneakyevil/IL2CPP_Resolver/assets/68436858/71460301-488a-45e2-a67c-8261537244d3)
